# Generated by Django 3.2.7 on 2021-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=11)),
                ('post_url', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=50)),
                ('food_score', models.FloatField()),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('post_id', 'keyword'), name='unique post and keyword'),
        ),
    ]
