# Generated by Django 3.2.7 on 2021-09-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='food_score',
            field=models.FloatField(default=0),
        ),
    ]
