# Generated by Django 3.2.7 on 2021-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_food_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['keyword'], name='posts_post_keyword_b2cd4d_idx'),
        ),
    ]
