# Generated by Django 3.2.7 on 2021-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_posts_post_keyword_b2cd4d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instas_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
