# Generated by Django 3.2.5 on 2021-11-20 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 20, 15, 42, 1, 484904)),
        ),
    ]
