# Generated by Django 3.2.7 on 2021-09-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210916_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='instas_analysis',
            new_name='insta_analysis',
        ),
    ]
