# Generated by Django 3.2.7 on 2021-09-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210917_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
    ]
